# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  Exclude:
    - 'db/ridgepole_export.rb'
    - 'config/initializers/cors.rb'
    - 'bin/*'

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true