# Steepfile
D = Steep::Diagnostic

target :app do
  signature "sig"
  check "app"
  check "lib"

  library "activesupport"
  library "activerecord"
  library "actionpack"
  library "actionview"
  library "pathname"
  library "cgi"

  configure_code_diagnostics(D::Ruby.default)
end
