module Alba
  module Resource
    module ClassMethods
      def attributes: (*Symbol) -> void
      def one: (Symbol, ?resource: untyped, ?key: Symbol) -> void
      def many: (Symbol, ?serializer: untyped) ?{ (untyped) -> void } -> void
      def attribute: (Symbol) ?{ (untyped) -> untyped } -> void
      def params: () -> Hash[Symbol, untyped]
      def new: (untyped, ?params: Hash[Symbol, untyped]) -> untyped
    end

    def params: () -> Hash[Symbol, untyped]
    def to_h: () -> Hash[String, untyped]
  end
end
